activityToCategory = {'Art Exhibitions':'Art and Culture', 
            'Beach Volleyball':'Sports and Fitness',
            'Concerts':'Music',
            'Cooking Classes':'Gastronomy',
            'Cultural Festivals':'Art and Culture',
            'Dancing Classes':'Music',
            'Escape Rooms':'Miscellaneous',
            'Food Tours':'Gastronomy',
            'Football Matches':'Sports and Fitness',
            'Group Cycling Tours':'Sports and Fitness',
            'Hiking Excursions':'Adventure',
            'Hot Air Balloon Rides':'Adventure',
            'Karaoke Nights':'Music',
            'Kayaking':'Sports and Fitness',
            'Pub Crawls':'Music',
            'River Cruises':'City Exploration',
            'Rock Climbing':'Sports and Fitness',
            'Scavenger Hunts':'Miscellaneous',
            'Segway Tours':'City Exploration',
            'Sightseeing Tours': 'City Exploration',
            'Snorkeling Tours': 'Adventure',
            'Theater Performances':'Art and Culture',
            'Theme Parks':'Miscellaneous',
            'Wine Tasting':'Gastronomy',
            'Zip Line Adventures':'Adventure'}

