activityToCategory = {'Art Exhibitions':'Art and Culture', 
            'Beach Volleyball':'Sports and Fitness',
            'Concerts':'Music',
            'Cooking Classes':'Gastronomy',
            'Cultural Festivals':'Art and Culture',
            'Dancing Classes':'Music',
            'Escape Rooms':'Miscellaneous',
            'Food Tours':'Gastronomy',
            'Football Matches':'Sports and Fitness',
            'Group Cycling Tours':'Sports and Fitness',
            'Hiking Excursions':'Adventure',
            'Hot Air Balloon Rides':'Adventure',
            'Karaoke Nights':'Music',
            'Kayaking':'Sports and Fitness',
            'Pub Crawls':'Music',
            'River Cruises':'City Exploration',
            'Rock Climbing':'Sports and Fitness',
            'Scavenger Hunts':'Miscellaneous',
            'Segway Tours':'City Exploration',
            'Sightseeing Tours': 'City Exploration',
            'Snorkeling Tours': 'Adventure',
            'Theater Performances':'Art and Culture',
            'Theme Parks':'Miscellaneous',
            'Wine Tasting':'Gastronomy',
            'Zip Line Adventures':'Adventure'}

categoryToActivity = {'Art and Culture': ['Art Exhibitions', 'Cultural Festivals', 'Theater Performances'], 
                      'Music': ['Concerts', 'Dancing Classes', 'Karaoke Nights', 'Pub Crawls'], 
                      'Adventure': ['Hiking Excursions', 'Hot Air Balloon Rides', 'Snorkeling Tours', 'Zip Line Adventures'], 
                      'Sports and Fitness': ['Beach Volleyball', 'Football Matches', 'Group Cycling Tours', 'Kayaking', 'Rock Climbing'], 
                      'Gastronomy': ['Cooking Classes', 'Food Tours', 'Wine Tasting'], 
                      'City Exploration': ['River Cruises', 'Segway Tours', 'Sightseeing Tours'], 
                      'Miscellaneous': ['Escape Rooms', 'Scavenger Hunts', 'Theme Parks']}
